"""P4.2 — Golden-context regression tests.

For each of the 5 documented turn lanes, we feed a fixed representative
"raw" pre-assembler context blob through ``assembler.assemble()`` and
compare the output bytes against a pinned snapshot in ``golden/``. Any
regression that adds (or drops) > 200 chars OR changes the kept-sections
list fails — preventing silent context bloat or accidental section loss.

Snapshots live in ``tests/golden/<lane>.txt`` and are regenerated by
running this file with ``GOLDEN_UPDATE=1`` set in the environment.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

GOLDEN_DIR = Path(__file__).parent / "golden"
DRIFT_TOLERANCE_BYTES = 200


# A fixed input blob covering the major section types live_brain_ctx
# emits. Identical for every lane so snapshots differ only by what the
# assembler keeps under each lane's byte budget + priority order.
FIXTURE_RAW_CONTEXT = (
    "RECENT RISK ACTIVITY:\n"
    "- 5m ago: shell — rm -rf /tmp/danger\n"
    "- pending patch (risk=0.8): /etc/foo.conf\n"
    "Confirm each of these was intended; the system did not block them.\n"
    "\n"
    "UNVERIFIED CLAIM:\n"
    "- claim: build passes — but no run recorded\n"
    "\n"
    "VERIFICATION REQUIRED:\n"
    "- /home/u/proj/main.py awaiting verify\n"
    "\n"
    "ACTIVE TASK:\n"
    "Wire P3.2 nucleus_bridge cross-plugin state.\n"
    "\n"
    "NEXT REQUIRED ACTION:\n"
    "Run the full live_brain_ctx test suite.\n"
    "\n"
    "MUST FOLLOW:\n"
    "- Plugin-only patches; no Hermes core edits.\n"
    "- E2E gate via Telegram CLI before declaring done.\n"
    "\n"
    "FILE KNOWLEDGE:\n"
    "- /home/u/proj/main.py: entrypoint, calls run_loop()\n"
    "- /home/u/proj/run_loop.py: main loop, polls every 10s\n"
    "\n"
    "RECALLED FIX:\n"
    "- 2026-04-02 (similar query): added timeout to httpx, fixed hang.\n"
    "\n"
    "KNOWN FACTS:\n"
    "- Provider is MiniMax-M2.7-highspeed.\n"
    "- Cache hit rate ~99% on stable turns.\n"
    "\n"
    "RECENT EPISODES:\n"
    "- 2026-05-18 21:00 — completed P5.1 prompt cache observability.\n"
    "- 2026-05-19 02:26 — wiring P3.2 bridge state.\n"
    "\n"
    "ACTIVE OBJECTIVES:\n"
    "- Land all remaining context perfection phases.\n"
    "\n"
    "VERIFIED ARTIFACTS:\n"
    "- /home/u/proj/notes.md (verified 1h ago)\n"
    "\n"
    "LIVE BRAIN POLICY:\n"
    "Stay laser-focused on the user's last imperative.\n"
)


LANES = [
    "chit_chat",
    "simple_execution",
    "deep_execution",
    "research_or_epistemic",
    "document_intake",
    "continuation_or_resume",
]


def _golden_path(lane: str) -> Path:
    return GOLDEN_DIR / f"{lane}.txt"


def _assemble_for(lane: str) -> str:
    from live_brain_ctx.modules.assembler import assemble
    out, _audit = assemble(
        FIXTURE_RAW_CONTEXT,
        turn_lane=lane,
        session_id="",  # disable cross-turn dedup so output is deterministic
        dedupe=False,
    )
    return out


def _kept_titles(rendered: str) -> list[str]:
    titles = []
    for line in rendered.splitlines():
        if line.endswith(":") and line.replace(":", "").strip().isupper():
            titles.append(line[:-1])
    return titles


def _update_golden(lane: str, rendered: str) -> None:
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    _golden_path(lane).write_text(rendered, encoding="utf-8")


def test_all_lanes_against_golden():
    update = os.environ.get("GOLDEN_UPDATE") == "1"
    failures: list[str] = []

    for lane in LANES:
        rendered = _assemble_for(lane)
        path = _golden_path(lane)
        if update or not path.exists():
            _update_golden(lane, rendered)
            print(f"✓ {lane}: golden written ({len(rendered)} bytes)")
            continue

        expected = path.read_text(encoding="utf-8")
        diff = abs(len(rendered) - len(expected))
        kept_now = _kept_titles(rendered)
        kept_then = _kept_titles(expected)

        if kept_now != kept_then:
            failures.append(
                f"{lane}: kept-section list changed.\n"
                f"  expected: {kept_then}\n"
                f"  got:      {kept_now}"
            )
            continue
        if diff > DRIFT_TOLERANCE_BYTES:
            failures.append(
                f"{lane}: byte drift {diff} > {DRIFT_TOLERANCE_BYTES} "
                f"(expected={len(expected)}, got={len(rendered)})"
            )
            continue
        print(f"✓ {lane}: {len(rendered)} bytes (Δ={diff}), kept={len(kept_now)} sections")

    assert not failures, "Golden context regressions:\n  " + "\n  ".join(failures)


def test_chit_chat_drops_everything_unprotected():
    """Chit-chat lane has budget=0 — only safety-protected sections survive."""
    rendered = _assemble_for("chit_chat")
    titles = _kept_titles(rendered)
    # Protected = priority < 10 (RECENT RISK ACTIVITY=1, UNVERIFIED CLAIM=2, …)
    assert "RECENT RISK ACTIVITY" in titles or rendered == "", (
        f"chit_chat must keep critical safety sections only, got: {titles}"
    )
    assert "RECENT EPISODES" not in titles
    assert "FILE KNOWLEDGE" not in titles
    print("✓ test_chit_chat_drops_everything_unprotected")


def test_deep_execution_keeps_more_than_simple():
    simple = _assemble_for("simple_execution")
    deep = _assemble_for("deep_execution")
    assert len(deep) >= len(simple), (
        f"deep_execution must keep at least as much as simple_execution: "
        f"deep={len(deep)} simple={len(simple)}"
    )
    deep_titles = _kept_titles(deep)
    simple_titles = _kept_titles(simple)
    assert set(deep_titles) >= set(simple_titles), (
        "deep_execution must be a superset of simple_execution sections"
    )
    print(f"✓ test_deep_execution_keeps_more_than_simple "
          f"(simple={len(simple)}, deep={len(deep)})")


def test_assembler_byte_caps_respected():
    """No emitted section may exceed its configured byte cap."""
    from live_brain_ctx.modules.assembler import _section_byte_cap
    rendered = _assemble_for("deep_execution")
    cur_title = None
    cur_body: list[str] = []
    sections: list[tuple[str, str]] = []
    for line in rendered.splitlines():
        if line.endswith(":") and line.replace(":", "").strip().isupper():
            if cur_title:
                sections.append((cur_title, "\n".join(cur_body)))
            cur_title = line[:-1]
            cur_body = []
        elif cur_title:
            cur_body.append(line)
    if cur_title:
        sections.append((cur_title, "\n".join(cur_body)))

    for title, body in sections:
        cap = _section_byte_cap(title)
        assert len(body) <= cap, (
            f"{title}: {len(body)} bytes exceeds cap {cap}"
        )
    print(f"✓ test_assembler_byte_caps_respected ({len(sections)} sections)")


if __name__ == "__main__":
    test_all_lanes_against_golden()
    test_chit_chat_drops_everything_unprotected()
    test_deep_execution_keeps_more_than_simple()
    test_assembler_byte_caps_respected()
    print("\nAll P4.2 golden-context tests passed.")
